import { Router } from "express";
import { userRouter } from "./user.router.js";
import { authRouter } from "./auth.router.js";
import { clientRouter } from "./client.router.js";
import { projectRouter } from "./project.router.js";
import { workOrderRouter } from "./work-order.router.js";
import { materialIndentItemRouter } from "./material-indent-item.router.js";
import { inventoryRouter } from "./inventory.router.js";
import { vendorRouter } from "./vendor.router.js";
import { vendorCategoryRouter } from "./vendor-category.router.js";
import { vendorRateContractRouter } from "./vendor-rate-contract.router.js";
import { subcontractorRouter } from "./subcontractor.router.js";
import { subcontractorRateContractRouter } from "./subcontractor-rate-contract.router.js";
import { roleRouter } from "./role.router.js";
import { moduleRouter } from "./module.router.js";
import { submoduleRouter } from "./submodule.router.js";
import { permissionRouter } from "./permission.router.js";
import { rolePermissionRouter } from "./role_permission.router.js";
import { employeeRouter } from "./employee.router.js";
import { attendanceRouter } from "./attendance.router.js";
import { leaveRequestRouter } from "./leave-request.router.js";
import { payrollRouter } from "./payroll.router.js";
import { reimbursementRouter } from "./reimbursement.router.js";
import { jobPostRouter } from "./job-post.router.js";
import { applicantRouter } from "./applicant.router.js";

const router = Router();

router.use("/auth", authRouter);
router.use("/users", userRouter);
router.use("/clients", clientRouter);
router.use("/projects", projectRouter);
router.use("/work-orders", workOrderRouter);
router.use("/material-indent-items", materialIndentItemRouter);
router.use("/inventories", inventoryRouter);
router.use("/vendor-categories", vendorCategoryRouter);
router.use("/vendors", vendorRouter);
router.use("/vendor-rate-contracts", vendorRateContractRouter);
router.use("/subcontractors", subcontractorRouter);
router.use("/subcontractor-rate-contracts", subcontractorRateContractRouter);
router.use("/roles", roleRouter);
router.use("/modules", moduleRouter);
router.use("/submodules", submoduleRouter);
router.use("/permissions", permissionRouter);
router.use("/role-permissions", rolePermissionRouter);
router.use("/employees", employeeRouter);
router.use("/attendance", attendanceRouter);
router.use("/leave-requests", leaveRequestRouter);
router.use("/payrolls", payrollRouter);
router.use("/reimbursements", reimbursementRouter);
router.use("/job-posts", jobPostRouter);
router.use("/applicants", applicantRouter);

export { router as apiRouter };
