import { Router } from 'express';
import { userRouter } from './hr/user.router.js';
import { authRouter } from './auth.router.js';
import { clientRouter } from './client.router.js';
import { projectRouter } from './projectMaster/project.router.js';
import { workOrderRouter } from './projectMaster/work-order.router.js';
import { materialIndentItemRouter } from './operation/material-indent-item.router.js';
import { inventoryRouter } from './inventory.router.js';
import { vendorRouter } from './vendor.router.js';
import { vendorCategoryRouter } from './vendor-category.router.js';
import { vendorRateContractRouter } from './vendor-rate-contract.router.js';
import { subcontractorRouter } from './operation/subcontractor.router.js';
import { subcontractorRateContractRouter } from './operation/subcontractor-rate-contract.router.js';
import { roleRouter } from './authority/role.router.js';
import { moduleRouter } from './authority/module.router.js';
import { submoduleRouter } from './authority/submodule.router.js';
import { permissionRouter } from './authority/permission.router.js';
import { rolePermissionRouter } from './authority/role_permission.router.js';
import { employeeRouter } from './hr/employee.router.js';
import { attendanceRouter } from './hr/attendance.router.js';
import { leaveRequestRouter } from './hr/leave-request.router.js';
import { payrollRouter } from './hr/payroll.router.js';
import { reimbursementRouter } from './hr/reimbursement.router.js';
import { jobPostRouter } from './hr/job-post.router.js';
import { applicantRouter } from './hr/applicant.router.js';
import { leaveRouter } from './hr/leave.router.js';

const router = Router();

router.use('/auth', authRouter);
router.use('/users', userRouter);
router.use('/clients', clientRouter);
router.use('/projects', projectRouter);
router.use('/work-orders', workOrderRouter);
router.use('/material-indent-items', materialIndentItemRouter);
router.use('/inventories', inventoryRouter);
router.use('/vendor-categories', vendorCategoryRouter);
router.use('/vendors', vendorRouter);
router.use('/vendor-rate-contracts', vendorRateContractRouter);
router.use('/subcontractors', subcontractorRouter);
router.use('/subcontractor-rate-contracts', subcontractorRateContractRouter);
router.use('/roles', roleRouter);
router.use('/modules', moduleRouter);
router.use('/submodules', submoduleRouter);
router.use('/permissions', permissionRouter);
router.use('/role-permissions', rolePermissionRouter);
router.use('/employees', employeeRouter);
router.use('/attendance', attendanceRouter);
router.use('/leave-requests', leaveRequestRouter);
router.use('/leaves', leaveRouter);
router.use('/payrolls', payrollRouter);
router.use('/reimbursements', reimbursementRouter);
router.use('/job-posts', jobPostRouter);
router.use('/applicants', applicantRouter);

export { router as apiRouter };
